source 'https://github.com/CocoaPods/Specs.git'

abstract_target 'defaults' do  
 
platform:ios, '10.0'

pod 'Masonry'
pod 'SVProgressHUD'
pod 'KVOController'
pod 'GPUImage'
pod 'CocoaAsyncSocket'
pod 'Addition'
pod 'UMengAnalytics'
pod 'MLeaksFinder'
pod 'FDFullscreenPopGesture'
pod 'YYKit'

target 'MQX'
target 'YMQ'

end
